CREATE TABLE Client(
	ID_Client int GENERATED BY DEFAULT AS IDENTITY,
	Client_Organization_Name varchar(100) not null,
	Client_Legal_Address varchar(100) null DEFAULT '-',
	Client_Physical_Address varchar(100) not null,
	Client_ITN varchar(11) not null UNIQUE constraint CH_Client_ITN
         CHECK(regexp_like(Client_ITN, '[0-9]{10}')),
	Client_BIC varchar(10) not null UNIQUE constraint CH_Client_BIC
    	CHECK(regexp_like(Client_BIC, '[0-9]{9}')) ,
	Client_OKPO varchar(11) not null UNIQUE constraint CH_Client_OKPO
		CHECK(regexp_like(Client_OKPO, '[0-9]{8}|[0-9]{10}')) ,
	Client_Repr_Surname varchar(30) not null,
	Client_Repr_Name varchar(30) not null,
	Client_Repr_Second_Name varchar(30) null DEFAULT '-'
);

CREATE TABLE Manager(
	ID_Manager int GENERATED BY DEFAULT AS IDENTITY,
	Manager_Surname varchar(30) not null,
	Manager_Name varchar(30) not null,
	Manager_Second_Name varchar(30) null DEFAULT '-',
	Manager_Passport_Series varchar(4) not null constraint CH_Manager_Passport_Series
    	CHECK(regexp_like(Manager_Passport_Series, '[0-9]{4}')),
	Manager_Passport_Number varchar(6) not null constraint CH_Manager_Passport_Number
    	CHECK(regexp_like(Manager_Passport_Number, '[0-9]{6}')),
	Manager_ITN varchar(10) not null UNIQUE constraint CH_Manager_ITN
    	CHECK(regexp_like(Manager_ITN, '[0-9]{10}')),
	Manager_SNILS varchar(14) not null UNIQUE constraint CH_Manager_SNILS
	CHECK(regexp_like(Manager_SNILS, '[0-9]{3}\\-[0-9]{3}\\-[0-9]{3} [0-9][0-9]'))
);

CREATE TABLE Driver(
	ID_Driver int GENERATED BY DEFAULT AS IDENTITY,
	Driver_Surname varchar(30) not null,
	Driver_Name varchar(30) not null,
	Driver_Second_Name varchar(30) null DEFAULT '-',
	Driver_Passport_Series varchar(4) not null constraint CH_Driver_Passport_Series
    	CHECK(regexp_like(Driver_Passport_Series, '[0-9]{4}')),
	Driver_Passport_Number varchar(6) not null constraint CH_Driver_Passport_Number
    CHECK(regexp_like(Driver_Passport_Number, '[0-9]{6}')),
	Driver_SNILS varchar(14) not null UNIQUE constraint CH_Driver_SNILS
    CHECK(regexp_like(Driver_SNILS, '[0-9]{3}\\-[0-9]{3}\\-[0-9]{3} [0-9][0-9]')),
	Driver_FFOMI varchar(16) not null UNIQUE constraint CH_Driver_FFOMI
    CHECK(regexp_like(Driver_FFOMI, '[0-9]{16}')),
	Driver_License_Series varchar(4) not null constraint CH_Driver_License_Series
    CHECK(regexp_like(Driver_License_Series, '[0-9]{4}')),
	Driver_License_Number varchar(6) not null constraint CH_Driver_License_Number
    CHECK(regexp_like(Driver_License_Number, '[0-9]{6}'))
);

CREATE TABLE Vehicle
(
        	ID_Vehicle int GENERATED BY DEFAULT AS IDENTITY,
        	Vehicle_Width int not null,
        	Vehicle_Height int not null,
       	Vehicle_Length int not null,
       	Vehicle_Capacity int not null,
       	Vehicle_State_Number varchar(10) not null constraint CH_Vehicle_State_Number
	CHECK(regexp_like(Vehicle_State_Number, '[А-Я]{2}[0-9]{3}[А-Я] [0-9]{2,3}'))
);

CREATE TABLE Complexity
(
        	ID_Complexity int GENERATED BY DEFAULT AS IDENTITY,
        	Complexity_Level int not null UNIQUE
);

CREATE TABLE Request(
	ID_Request int GENERATED BY DEFAULT AS IDENTITY,
	Request_Number int not null,
	Manager_ID int not null REFERENCES Manager (ID_Manager),
	Client_ID int not null REFERENCES Client (ID_Client),
	Request_Date date null DEFAULT(CURRENT_DATE),
	Request_Time TIME null DEFAULT(CURRENT_TIMESTAMP)
);

CREATE TABLE Cargo(
	ID_Cargo int GENERATED BY DEFAULT AS IDENTITY,
	Cargo_Description varchar(200) not null,
	Request_ID int not null REFERENCES Request (ID_Request),
	Cargo_Width int not null,
	Cargo_Height int not null,
	Cargo_Length int not null,
	Cargo_Weight int not null,
	Cargo_Price int null DEFAULT 0
);

CREATE TABLE Delivery_Point(
	ID_Delivery_Point int GENERATED BY DEFAULT AS IDENTITY,
	Delivery_Point_Mark varchar(1) null DEFAULT '-' constraint CH_Delivery_Point_Mark
    	CHECK(regexp_like(Delivery_Point_Mark, '[+]|[-]')),
	Request_ID int not null REFERENCES Request (ID_Request),
	Delivery_Point_Destination varchar(200) not null
);

CREATE TABLE Route_Sheet(
	ID_Route_Sheet int GENERATED BY DEFAULT AS IDENTITY,
	Route_Sheet_Number int not null,
	Complexity_ID int not null REFERENCES Complexity (ID_Complexity),
	Vehicle_ID int not null REFERENCES Vehicle (ID_Vehicle),
	Driver_ID int not null REFERENCES Driver (ID_Driver),
	Route_Sheet_Date Date null DEFAULT(CURRENT_TIMESTAMP)
);

CREATE TABLE Combination_Route_Sheet_Delivery_Point(
	ID_Combination_Route_Sheet_Delivery_Point int GENERATED BY DEFAULT AS IDENTITY,
	Route_Sheet_ID int not null REFERENCES Route_Sheet (ID_Route_Sheet),
	Delivery_Point_ID int not null REFERENCES Delivery_Point (ID_Delivery_Point)
);

CREATE TABLE Combination_Route_Sheet_Cargo(
	ID_Combination_Route_Sheet_Cargo int GENERATED BY DEFAULT AS IDENTITY,
	Route_Sheet_ID int not null REFERENCES Route_Sheet (ID_Route_Sheet),
	Cargo_ID int not null REFERENCES Cargo (ID_Cargo)
);


--Изменение регулярных выражений
alter table Manager Drop constraint CH_Manager_SNILS,
Add constraint CH_Manager_SNILS CHECK(regexp_like(Manager_SNILS, '[0-9]{3}\\-[0-9]{3}\\-[0-9]{3} [0-9][0-9]'))


alter table Driver Drop constraint CH_Driver_SNILS,
Add constraint CH_Driver_SNILS CHECK(regexp_like(Driver_SNILS, '[0-9]{3}\\-[0-9]{3}\\-[0-9]{3} [0-9][0-9]'))