create table Employee
(
	ID_Employee int generated by default as identity,
	Second_Name varchar (30) not null,
	First_Name varchar (30) not null,
	Middle_Name varchar (30) default ('Нет данных'),
	Employee_Phone varchar(17) not null,
    constraint PK_Employee primary key (ID_Employee),
    constraint UQ_Employee_Phone unique (Employee_Phone),
	constraint CH_Employee_Phone check (regexp_like(Employee_Phone, '\+7\([0-9]{3}\)[0-9]{3}\-[0-9]{2}\-[0-9]{2}'))
);