create user C##Client identified by "Pa$$w0rd";
grant connect to C##Client;
grant create session to C##Client;

create user C##Driver identified by "Pa$$w0rd";
grant connect to C##Driver;
grant create session to C##Driver;

create user C##Manager identified by "Pa$$w0rd";
grant connect to C##Manager;
grant create session to C##Manager;

create user C##GC_Admin identified by "Pa$$w0rd";
grant connect to C##GC_Admin;
grant create session to C##GC_Admin;


create public SYNONYM Cargo for Cargo;
create public SYNONYM cargo_delete for cargo_delete;
create public SYNONYM cargo_insert for cargo_insert;
create public SYNONYM cargo_update for cargo_update;
create public SYNONYM Choose_Vehicle_For_Cargo for Choose_Vehicle_For_Cargo;
create public SYNONYM Client for Client;
create public SYNONYM client_delete for client_delete;
create public SYNONYM client_insert for client_insert;
create public SYNONYM client_update for client_update;
create public SYNONYM Combination_Route_Sheet_Cargo for Combination_Route_Sheet_Cargo;
create public SYNONYM combination_route_sheet_cargo_delete for combination_route_sheet_cargo_delete;
create public SYNONYM combination_route_sheet_cargo_insert for combination_route_sheet_cargo_insert;
create public SYNONYM combination_route_sheet_cargo_update for combination_route_sheet_cargo_update;
create public SYNONYM Combination_Route_Sheet_Delivery_Point for Combination_Route_Sheet_Delivery_Point;
create public SYNONYM combination_route_sheet_delivery_point_delete for combination_route_sheet_delivery_point_delete;
create public SYNONYM combination_route_sheet_delivery_point_insert for combination_route_sheet_delivery_point_insert;
create public SYNONYM combination_route_sheet_delivery_point_update for combination_route_sheet_delivery_point_update;
create public SYNONYM Complexity for Complexity;
create public SYNONYM complexity_delete for complexity_delete;
create public SYNONYM complexity_insert for complexity_insert;
create public SYNONYM complexity_update for complexity_update;
create public SYNONYM Delivery_point for Delivery_point;
create public SYNONYM delivery_point_delete for delivery_point_delete;
create public SYNONYM delivery_point_insert for delivery_point_insert;
create public SYNONYM delivery_point_update for delivery_point_update;
create public SYNONYM Driver for Driver;
create public SYNONYM driver_delete for driver_delete;
create public SYNONYM driver_insert for driver_insert;
create public SYNONYM Driver_List for Driver_List;
create public SYNONYM driver_update for driver_update;
create public SYNONYM Manager for Manager;
create public SYNONYM manager_delete for manager_delete;
create public SYNONYM manager_insert for manager_insert;
create public SYNONYM manager_update for manager_update;
create public SYNONYM Request for Request;
create public SYNONYM request_delete for request_delete;
create public SYNONYM request_insert for request_insert;
create public SYNONYM Request_List for Request_List;
create public SYNONYM request_update for request_update;
create public SYNONYM Route_Sheet for Route_Sheet;
create public SYNONYM route_sheet_delete for route_sheet_delete;
create public SYNONYM route_sheet_insert for route_sheet_insert;
create public SYNONYM Route_Sheet_List for Route_Sheet_List;
create public SYNONYM route_sheet_update for route_sheet_update;
create public SYNONYM Vehicle for Vehicle;
create public SYNONYM vehicle_delete for vehicle_delete;
create public SYNONYM vehicle_insert for vehicle_insert;
create public SYNONYM Vehicle_List for Vehicle_List;
create public SYNONYM vehicle_update for vehicle_update;




grant SELECT on Cargo to C##Client;
grant SELECT on Delivery_Point to C##Client;
grant EXECUTE on cargo_delete to C##Client;
grant EXECUTE on cargo_insert to C##Client;
grant EXECUTE on cargo_update to C##Client;
grant EXECUTE on client_delete to C##Client;
grant EXECUTE on client_update to C##Client;
grant EXECUTE on delivery_point_delete to C##Client;
grant EXECUTE on delivery_point_insert to C##Client;
grant EXECUTE on delivery_point_update to C##Client;
grant EXECUTE on request_delete to C##Client;
grant EXECUTE on request_insert to C##Client;
grant EXECUTE on request_update to C##Client;
grant SELECT on Request_List to C##Client;


grant SELECT on Complexity to C##Driver;
grant SELECT on Delivery_Point to C##Driver;
grant SELECT on Vehicle to C##Driver;
grant execute on driver_insert to C##Driver;
grant execute on driver_update to C##Driver;
grant SELECT on Route_Sheet_List to C##Driver;
grant SELECT on Vehicle_List to C##Driver;


grant SELECT on Cargo to C##Manager;
grant SELECT on Client to C##Manager;
grant SELECT on Combination_Route_Sheet_Cargo to C##Manager;
grant SELECT on Combination_Route_Sheet_Delivery_Point to C##Manager;
grant SELECT on Complexity to C##Manager;
grant SELECT on Delivery_point to C##Manager;
grant SELECT on Driver to C##Manager;
grant SELECT on Request to C##Manager;
grant SELECT on Route_Sheet to C##Manager;
grant SELECT on Vehicle to C##Manager;
grant execute on cargo_delete to C##Manager;
grant execute on cargo_insert to C##Manager;
grant execute on cargo_update to C##Manager;
grant execute on client_delete to C##Manager;
grant execute on client_insert to C##Manager;
grant execute on client_update to C##Manager;
grant execute on combination_route_sheet_cargo_delete to C##Manager;
grant execute on combination_route_sheet_cargo_insert to C##Manager;
grant execute on combination_route_sheet_cargo_update to C##Manager;
grant execute on combination_route_sheet_delivery_point_delete to C##Manager;
grant execute on combination_route_sheet_delivery_point_insert to C##Manager;
grant execute on combination_route_sheet_delivery_point_update to C##Manager;
grant execute on complexity_delete to C##Manager;
grant execute on complexity_insert to C##Manager;
grant execute on complexity_update to C##Manager;
grant execute on delivery_point_delete to C##Manager;
grant execute on delivery_point_insert to C##Manager;
grant execute on delivery_point_update to C##Manager;
grant execute on driver_delete to C##Manager;
grant execute on driver_insert to C##Manager;
grant execute on driver_update to C##Manager;
grant execute on manager_update to C##Manager;
grant execute on request_delete to C##Manager;
grant execute on request_insert to C##Manager;
grant execute on request_update to C##Manager;
grant execute on route_sheet_delete to C##Manager;
grant execute on route_sheet_insert to C##Manager;
grant execute on route_sheet_update to C##Manager;
grant execute on vehicle_delete to C##Manager;
grant execute on vehicle_insert to C##Manager;
grant execute on vehicle_update to C##Manager;
grant SELECT on Driver_List to C##Manager;
grant SELECT on Vehicle_List to C##Manager;
grant execute on Choose_Vehicle_For_Cargo to C##Manager;


grant SELECT on Cargo to C##GC_Admin;
grant SELECT on Client to C##GC_Admin;
grant SELECT on Combination_Route_Sheet_Cargo to C##GC_Admin;
grant SELECT on Combination_Route_Sheet_Delivery_Point to C##GC_Admin;
grant SELECT on Complexity to C##GC_Admin;
grant SELECT on Delivery_point to C##GC_Admin;
grant SELECT on Driver to C##GC_Admin;
grant SELECT on Manager to C##GC_Admin;
grant SELECT on Request to C##GC_Admin;
grant SELECT on Route_Sheet to C##GC_Admin;
grant SELECT on Vehicle to C##GC_Admin;
grant execute on cargo_delete to C##GC_Admin;
grant execute on cargo_insert to C##GC_Admin;
grant execute on cargo_update to C##GC_Admin;
grant execute on client_delete to C##GC_Admin;
grant execute on client_insert to C##GC_Admin;
grant execute on client_update to C##GC_Admin;
grant execute on combination_route_sheet_cargo_delete to C##GC_Admin;
grant execute on combination_route_sheet_cargo_insert to C##GC_Admin;
grant execute on combination_route_sheet_cargo_update to C##GC_Admin;
grant execute on combination_route_sheet_delivery_point_delete to C##GC_Admin;
grant execute on combination_route_sheet_delivery_point_insert to C##GC_Admin;
grant execute on combination_route_sheet_delivery_point_update to C##GC_Admin;
grant execute on complexity_delete to C##GC_Admin;
grant execute on complexity_insert to C##GC_Admin;
grant execute on complexity_update to C##GC_Admin;
grant execute on delivery_point_delete to C##GC_Admin;
grant execute on delivery_point_insert to C##GC_Admin;
grant execute on delivery_point_update to C##GC_Admin;
grant execute on driver_delete to C##GC_Admin;
grant execute on driver_insert to C##GC_Admin;
grant execute on driver_update to C##GC_Admin;
grant execute on manager_delete to C##GC_Admin;
grant execute on manager_insert to C##GC_Admin;
grant execute on manager_update to C##GC_Admin;
grant execute on request_delete to C##GC_Admin;
grant execute on request_insert to C##GC_Admin;
grant execute on request_update to C##GC_Admin;
grant execute on route_sheet_delete to C##GC_Admin;
grant execute on route_sheet_insert to C##GC_Admin;
grant execute on route_sheet_update to C##GC_Admin;
grant execute on vehicle_delete to C##GC_Admin;
grant execute on vehicle_insert to C##GC_Admin;
grant execute on vehicle_update to C##GC_Admin;
grant SELECT on Driver_List to C##GC_Admin;
grant SELECT on Request_List to C##GC_Admin;
grant SELECT on Route_Sheet_List to C##GC_Admin;
grant SELECT on Vehicle_List to C##GC_Admin;
grant execute on Choose_Vehicle_For_Cargo to C##GC_Admin;
